#!/usr/bin/env bash
# This script checks if a host is reachable on the network by sending 5 ICMP echo requests (ping).
# Usage: ./5-is_the_host_on_the_network {IP_ADDRESS}

if [ -z "$1" ]; then
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else 
ping -c 5 "$1"
fi
