#!/usr/bin/env bash
# Prepend two lines to /etc/hosts in-place without renaming the file.

{
  printf '127.0.0.2 localhost\n'
  printf '8.8.8.8 facebook.com\n'
  cat /etc/hosts
} | tee /etc/hosts >/dev/null
